name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install dependencies
      run: npm install
    - name: run integration tests
      run: npm test

  security-audit:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Fix Security Issues (force)
        run: npm audit fix --force

      - name: Run Security Audit
        run: npm audit