name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm install
    - name: run tests
      run: npm test

  security-audit:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Fix Security Issues (force)
        run: npm audit fix --force

      - name: Run Security Audit
        run: npm audit


  deploy:
    runs-on: ubuntu-latest
    needs: security-audit
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
